import pkg_resources


MODELS_DIR = "models"
MODEL_FILENAME = "latest_model.pt"
MYELIN_MODEL_PATH = MODELS_DIR + '/myelin/' + MODEL_FILENAME

OPENVINO_MODEL_DIR_NAME = "latest_model_openvino_model/"
OPENVINO_MODEL_PATH = MODELS_DIR + '/myelin/' + OPENVINO_MODEL_DIR_NAME

IMG_SIZE = 1024

OPENVINO_BACKEND_PREFIX = "OpenVINO" 
OPENVINO_BACKEND_GPU = OPENVINO_BACKEND_PREFIX + "-GPU"
OPENVINO_BACKEND_CPU = OPENVINO_BACKEND_PREFIX + "-CPU"