import pkg_resources


MODELS_DIR = "models"
MYELIN_MODEL_FILENAME = "latest_model.pt"
AXON_MODEL_FILENAME = "axon_model_20250512.pt"
MYELIN_MODEL_PATH = MODELS_DIR + '/myelin/' + MYELIN_MODEL_FILENAME
AXON_MODEL_PATH = MODELS_DIR + '/axons/' + AXON_MODEL_FILENAME
AXON_MODEL_NAME = "stardist"

OPENVINO_MYELIN_MODEL_DIR_NAME = "latest_model_openvino_model/"
OPENVINO_MYELIN_MODEL_PATH = MODELS_DIR + '/myelin/' + OPENVINO_MYELIN_MODEL_DIR_NAME
OPENVINO_AXON_MODEL_DIR_NAME = "axon_model_20250512_openvino_model/"
OPENVINO_AXONS_MODEL_PATH = MODELS_DIR + '/axons/' + OPENVINO_AXON_MODEL_DIR_NAME


IMG_SIZE = 1024

OPENVINO_BACKEND_PREFIX = "OpenVINO" 
OPENVINO_BACKEND_GPU = OPENVINO_BACKEND_PREFIX + "-GPU"
OPENVINO_BACKEND_CPU = OPENVINO_BACKEND_PREFIX + "-CPU"